name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build (for Pull Requests, use refs/pull/NNN/head)'
        required: true
  release:
    types:
    - published

jobs:
  source:
    name: Source

    uses: ./.github/workflows/release-source.yml
    secrets: inherit

  linux:
    name: Linux (Generic)
    needs: source

    uses: ./.github/workflows/release-linux.yml
    secrets: inherit
    with:
      steamworks_sdk_version: 158a

  macos:
    name: MacOS
    needs: source

    uses: ./.github/workflows/release-macos.yml
    secrets: inherit
    with:
      steamworks_sdk_version: 158a

  windows:
    name: Windows
    needs: source

    uses: ./.github/workflows/release-windows.yml
    secrets: inherit
    with:
      steamworks_sdk_version: 158a

  upload-cdn:
    name: Upload (CDN)
    needs:
    - source
    - linux
    - macos
    - windows

    if: github.event_name == 'release'

    uses: ./.github/workflows/upload-cdn.yml
    secrets: inherit

    with:
      version: ${{ needs.source.outputs.version }}

  upload-github:
    name: Upload (GitHub)
    needs:
    - source
    - linux
    - macos
    - windows

    if: github.event_name == 'release'

    uses: ./.github/workflows/upload-github.yml
    secrets: inherit

    with:
      version: ${{ needs.source.outputs.version }}
